# Qianjun Ding 1080391 
# Zhiyuan Gao 1068184 
# Jiachen Li 1068299 
# Yanting Mu 1068314
# Chi Zhang 1067750

- name: delete previous app process
  ansible.builtin.command: sudo pkill -f app.py

- name: run app from Worker
  become: yes
  # shell: sudo python3 CCCA2/Worker/app.py {{ groups['instance1ip'][0] }} {{ groups['instance3ip'][0] }}

  shell: nohup python3 -u CCCA2/Worker/app.py {{ groups['instance3ip'][0] }} >log.txt & 