# 1. Create instances 
# 2. Attach volumes to an instance 
# 3. Attach security group to an instance 

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: key
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 50
  - vol_name: vol-2
    vol_size: 50
  #- vol_name: vol-2-1
  #  vol_size: 10
  #- vol_name: vol-2-2
  #  vol_size: 10

# Security group
security_groups:
  - name: instance_ssh
    description: "instance security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: instance_http
    description: "instance security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance1
    volumes: ['vol-1']
  - name: instance2
    volumes: ['vol-2']


