--- 
# Install dependencies on instances
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get isntall python3-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

# Follows https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# In order to prepare for docker

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['git', 'python3-dev', 'python3-setuptools', 'curl', 'software-properties-common', 'virtualenv', 'ca-certificates', 'apt-transport-https']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
