--- 
# Group 1 Melbourne
# Qianjun Ding 1080391 
# Zhiyuan Gao 1068184 
# Jiachen Li 1068299 
# Yanting Mu 1068314
# Chi Zhang 1067750

# Install dependencies on instances
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get isntall python3-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

# Follows https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# In order to prepare for docker

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['git', 'python3-dev', 'python3-setuptools', 'curl', 'software-properties-common', 'virtualenv', 'ca-certificates', 'apt-transport-https']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install python dependencies
  become: yes 
  ansible.builtin.pip:
    name: ['requests', 'CouchDB', 'Flask-CouchDB', 'flask-mysql', 'emot', 'nltk', 'tweepy', 'flask_cors', 'gunicorn']
    state: latest