# Group 1 Melbourne
# Qianjun Ding 1080391 
# Zhiyuan Gao 1068184 
# Jiachen Li 1068299 
# Yanting Mu 1068314
# Chi Zhang 1067750

# Modified from https://github.com/andrewrothstein/ansible-docker-couchdb/blob/master/tasks/main.yml
# - name: remove container 
#   become: yes
#   docker_container: 
#     name: ohno
#     state: absent

- name: Launch couchdb via docker container 
  become: yes 
  docker_container: 
    name: "Worker1"
    image: "{{ docker_couchdb_image }}{{ docker_couchdb_VERSION }}"
    ports: 
      - "{{ docker_couchdb_host_port }}:{{ docker_couchdb_host_port }}"
      - "9100-9200:9100-9200"
      - "4369:4369" 
      - "5986:5986"
    # Modified from 14-4-22-workshop3
    env: 
      COUCHDB_USER: "{{ docker_couchdb_user }}"
      COUCHDB_PASSWORD: "{{ docker_couchdb_password }}"
      NODENAME: "couchdb@{{ groups['instance2ip'][0] }}"
      COUCHDB_SECRET: "{{ docker_couchdb_cookie }}"
      ERL_FLAGS: "-setcookie '{{docker_couchdb_cookie}}' -name couchdb@{{ groups['instance2ip'][0] }} -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200"
      
  

