---
# Create an instance on NeCTAR
- name: Create an instance
  openstack.cloud.server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  ansible.builtin.wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Follow https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
# Create an inventory file for later use 
- name: Create an inventory file 
  ansible.builtin.copy:
    dest: "inventory/host.ini"
    content: "[instances]\n"

# Follow https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
# Save ips of different instances into an inventory file 
- name: Record ips to Inventory
  ansible.builtin.lineinfile: 
    path: "inventory/host.ini"
    line: "ubuntu@{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined


# From https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
# Retreve facts about the instance 
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts
