# Modified from http://wiki.ruanbekker.com/index.php/Git_with_Ansible
#- name: create .ssh directory 
#  file: 
#    path: /home/ubuntu/.ssh
#    state: directory 
#    owner: ubuntu
#    group: ubuntu
#    mode: 0600

- name: Creates main directory
  file:
    path: '{{ remote_folder }}'
    state: directory

- name: places keys in path
  become: yes
  copy:
    src: id_rsa
    dest: '{{ git_private_key }}'
    mode: 0644
    owner: ubuntu
    group: ubuntu
# Copy private GitHub key to MRC

# - name: add ssh git_key 
#  shell: ssh-add git_key

- name: clone to path.
  git:
    repo: https://github.com/Valkyriean/CCCA2
    dest: CCCA2
    accept_hostkey: yes
    key_file: git_key
    update: yes 
    force: yes
  become: yes
# git clone https://github.com/Valkyriean/CCCA2

- name: delete deploy key
  file:
    path: '{{ git_private_key }}'
    state: absent