# Qianjun Ding 1080391 
# Zhiyuan Gao 1068184 
# Jiachen Li 1068299 
# Yanting Mu 1068314
# Chi Zhang 1067750

# Modified from https://gist.github.com/devynspencer/effa29af449c46477ac71213210e7043
- name: places key in path
  become: yes
  ansible.builtin.copy:
    src: 'keys/id_rsa'
    dest: '{{ git_private_key }}'
    mode: 0644
    owner: '{{ user }}'
    group: '{{ user }}'

- name: configure ssh to use ansible key for github 
  ansible.builtin.template: 
    src: 'templates/ssh_config.j2'
    dest: /home/ubuntu/.ssh/config
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644

# Followed by https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: clone private repo to path
  ansible.builtin.git:
    repo: git@github.com:Valkyriean/CCCA2.git
    dest: CCCA2
    accept_hostkey: yes
    key_file: '{{ git_private_key }}'
    update: yes 
    force: yes
  become: yes
# git clone https://github.com/Valkyriean/CCCA2

# Delete github key from MRC after cloning to ensure secruity 
- name: delete deploy key
  ansible.builtin.file:
    path: '{{ git_private_key }}'
    state: absent