- name: delete previous app process
  shell: pkill -f gunicorn

- name: run app from Gateway
  # shell: python3 CCCA2/Gateway/app.py
  shell: cd CCCA2/Gateway; python3 -m gunicorn --bind 0.0.0.0:3000 --workers=2 app:app