# Qianjun Ding 1080391 
# Zhiyuan Gao 1068184 
# Jiachen Li 1068299 
# Yanting Mu 1068314
# Chi Zhang 1067750

- hosts: instance4
  vars_files: 
    - host_vars/instance_setup.yaml
  gather_facts: true 

  roles: 
  - role: deploy-worker3