---
- hosts: instances 
  vars_files: 
    - host_vars/instance_setup.yaml
  gather_facts: true 

  roles: 
  #- role: install-instance-requirements
  #- role: clone-github
  - role: install-docker

  



