---
- hosts: instances 
  vars_files: 
    - host_vars/instance_setup.yaml
    - host_vars/docker_couchdb.yaml
  gather_facts: true 

  roles: 
  # - role: install-instance-requirements
  #- role: clone-github
  #- role: install-docker
  - role: launch-docker-couchdb

  



